-- MySQL Script generated by MySQL Workbench
-- seg 07 dez 2020 04:06:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sys_edu_development
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sys_edu_development
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sys_edu_development` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sys_edu_development` ;

-- -----------------------------------------------------
-- Table `sys_edu_development`.`ar_internal_metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`ar_internal_metadata` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`ar_internal_metadata` (
  `key` VARCHAR(255) NOT NULL,
  `value` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`classrooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`classrooms` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`classrooms` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `grade` INT NULL DEFAULT NULL,
  `letter` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`secretaries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`secretaries` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`secretaries` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `coordinator` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`schools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`schools` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`schools` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `addressSchool` VARCHAR(255) NULL DEFAULT NULL,
  `nameSchool` VARCHAR(255) NULL DEFAULT NULL,
  `director` VARCHAR(255) NULL DEFAULT NULL,
  `secretary_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_schools_on_secretary_id` (`secretary_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_2234da67e8`
    FOREIGN KEY (`secretary_id`)
    REFERENCES `sys_edu_development`.`secretaries` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`professors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`professors` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`professors` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nameProfessor` VARCHAR(255) NULL DEFAULT NULL,
  `school_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_professors_on_school_id` (`school_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_7b91075d47`
    FOREIGN KEY (`school_id`)
    REFERENCES `sys_edu_development`.`schools` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`subjects` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`subjects` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nameSubject` VARCHAR(255) NULL DEFAULT NULL,
  `professor_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_subjects_on_professor_id` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_bbcb717737`
    FOREIGN KEY (`professor_id`)
    REFERENCES `sys_edu_development`.`professors` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`classrooms_subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`classrooms_subjects` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`classrooms_subjects` (
  `classroom_id` BIGINT NOT NULL,
  `subject_id` BIGINT NOT NULL,
  INDEX `index_classrooms_subjects_on_classroom_id_and_subject_id` (`classroom_id` ASC, `subject_id` ASC) VISIBLE,
  INDEX `index_classrooms_subjects_on_subject_id_and_classroom_id` (`subject_id` ASC, `classroom_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_4c3eb6a053`
    FOREIGN KEY (`subject_id`)
    REFERENCES `sys_edu_development`.`subjects` (`id`),
  CONSTRAINT `fk_rails_f4c83af6f7`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `sys_edu_development`.`classrooms` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`equip_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`equip_types` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`equip_types` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`equipment` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`equipment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `availability` TINYINT(1) NULL DEFAULT NULL,
  `secretary_id` BIGINT NOT NULL,
  `equip_type_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_equipment_on_secretary_id` (`secretary_id` ASC) VISIBLE,
  INDEX `index_equipment_on_equip_type_id` (`equip_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_679322e890`
    FOREIGN KEY (`secretary_id`)
    REFERENCES `sys_edu_development`.`secretaries` (`id`),
  CONSTRAINT `fk_rails_f88b246304`
    FOREIGN KEY (`equip_type_id`)
    REFERENCES `sys_edu_development`.`equip_types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`responsibles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`responsibles` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`responsibles` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cpfResp` VARCHAR(255) NULL DEFAULT NULL,
  `addressResp` VARCHAR(255) NULL DEFAULT NULL,
  `nameResp` VARCHAR(255) NULL DEFAULT NULL,
  `income` FLOAT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`fines`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`fines` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`fines` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `value` FLOAT NULL DEFAULT NULL,
  `reasonFine` VARCHAR(255) NULL DEFAULT NULL,
  `secretary_id` BIGINT NOT NULL,
  `responsible_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_fines_on_secretary_id` (`secretary_id` ASC) VISIBLE,
  INDEX `index_fines_on_responsible_id` (`responsible_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_71f283b0cf`
    FOREIGN KEY (`secretary_id`)
    REFERENCES `sys_edu_development`.`secretaries` (`id`),
  CONSTRAINT `fk_rails_ca254641b2`
    FOREIGN KEY (`responsible_id`)
    REFERENCES `sys_edu_development`.`responsibles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`requisitions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`requisitions` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`requisitions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `reasonReq` VARCHAR(255) NULL DEFAULT NULL,
  `responsible_id` BIGINT NOT NULL,
  `equipment_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_requisitions_on_responsible_id` (`responsible_id` ASC) VISIBLE,
  INDEX `index_requisitions_on_equipment_id` (`equipment_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_099f52bb6a`
    FOREIGN KEY (`responsible_id`)
    REFERENCES `sys_edu_development`.`responsibles` (`id`),
  CONSTRAINT `fk_rails_1555caec1f`
    FOREIGN KEY (`equipment_id`)
    REFERENCES `sys_edu_development`.`equipment` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`schema_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`schema_migrations` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`schema_migrations` (
  `version` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sys_edu_development`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sys_edu_development`.`students` ;

CREATE TABLE IF NOT EXISTS `sys_edu_development`.`students` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nameStudent` VARCHAR(255) NULL DEFAULT NULL,
  `classroom_id` BIGINT NOT NULL,
  `responsible_id` BIGINT NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `updated_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_students_on_classroom_id` (`classroom_id` ASC) VISIBLE,
  INDEX `index_students_on_responsible_id` (`responsible_id` ASC) VISIBLE,
  CONSTRAINT `fk_rails_4fde1dad9c`
    FOREIGN KEY (`classroom_id`)
    REFERENCES `sys_edu_development`.`classrooms` (`id`),
  CONSTRAINT `fk_rails_db0031ee5a`
    FOREIGN KEY (`responsible_id`)
    REFERENCES `sys_edu_development`.`responsibles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
